# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['PG_DB_USER'] %>
  password: <%= ENV['PG_DB_PASS'] %>

development:
  <<: *common
  database: <%= ENV['PG_DB_NAME'] %>
  host: localhost

staging:
  <<: *common
  database: <%= ENV['PG_DB_NAME'] %>

test: &test
  <<: *common
  database: personalblog_test
